- name: Evaluate Pod Monitor
  k8s:
    state: present
    namespace: '{{ cluster_project}}'
    resource_definition: "{{ lookup('template', 'strimzi_pod_monitor.yml.j2') }}"

- name: Get a list of all Secret objects
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    namespace: '{{ cluster_project }}'
  register: secrets_list

- name: get length of list
  ansible.builtin.set_fact:
    list_len: "{{ secrets_list.resources | length }}"

- name: set an int
  ansible.builtin.set_fact:
    int_length: (list_len | int)

- name: write list_len
  ansible.builtin.debug:
    var: int_length

- name: iterate over secrets list
  ansible.builtin.set_fact:
    secret_name: "{{ secrets_list.resources[item]['metadata']['name'] }}"
  loop: "{{ query('sequence', 'start=0 end=int_length | string') }}"
  when: secrets_list.resources[item]['metadata']['name'] | regex_search('grafana-serviceaccount-token.*') != -1
  until: secret_name is defined

- name: debug 0 index further
  ansible.builtin.debug:
    var: secrets_list.resources[0]['metadata']['name']

- name: Iterate over list of secrets until the correct string is found 
  ansible.builtin.set_fact:
    secret_name: "{{ item }}"
  loop: "{{ secrets_list2 }}"
  when: "{{ item | regex_search('grafana-serviceaccount-token.') }}"

- name: Get Grafana ServiceAccount Token
  k8s_info:
    kind: Secret
    name:  "{{ secret_name }}"
    namespace: '{{ cluster_project }}'
    api_version: v1
  register: r_grafana_secret
  until:
    - r_grafana_secret.resources is defined
  retries: 10
  delay: 15

- name: Set grafana token
  set_fact:
    grafana_token: '{{ r_grafana_secret.resources[0].data.token | b64decode }}'
  when:
    - r_grafana_secret.resources[0].data.token is defined

- name: Evaluate Grafana ServiceAccount permissons
  k8s:
    state: present
    api_version: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    definition:
      metadata:
        name: thanos-metric-viewer
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-monitoring-view
      subjects:
      - kind: ServiceAccount
        name: grafana-serviceaccount
        namespace: '{{ cluster_project }}'

- name: Evaluate Grafana Datasource
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'grafana_datasource.yml.j2') }}"

- name: Evaluate Kafka Dashboard
  k8s:
    state: present
    namespace: '{{ cluster_project}}'
    resource_definition: "{{ lookup('file', 'grafana_kafka_dashboard.yml') }}"
