- name: Provision User Monitoring
  ansible.builtin.include_tasks: provision_monitoring.yml
  when:
    - not delete_demo

- name: Configure User Monitoring
  ansible.builtin.include_tasks: configure_monitoring.yml
  when:
    - not delete_demo
