- name: Evaluate Users
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('file', item) }}"
  loop:
    - consumer-user.yml
    - producer-user.yml
    - kafka-ui_user.yml

- name: Evaluate Topics
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('file', item) }}"
  loop:
    - quote-topic.yml
    - quote-request-topic.yml
    - movies-topic.yml

- name: Evaluate Kafka Connect Cluster
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('template', 'kafka-connect-cluster.yml.j2') }}"

- name: Evaluate Kafka Connector
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('file', 'connector.yml') }}"
