- name: Evaluate Users
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('file', item) }}"
  loop:
    - processor-user.yml
    - producer-user.yml
    - kafka-ui_user.yml

- name: Evaluate a_quotes Topic
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('file', item) }}"
  loop:
    - quote-topic.yml
    - quote-request-topic.yml
