apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: consumer
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: a_quote_requests
          patternType: literal
        host: "*"
        operations: 
          - Read
          - Describe
      - resource:
          type: group
          name: a_request_group
          patternType: literal
        operations: 
          - Read
        host: "*"
      - resource:
          type: topic
          name: a_quotes
          patternType: literal
        operations: 
          - Write
          - Describe
        host: "*"
