apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: ui
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations: 
          - Read
          - DescribeConfigs
        host: "*"
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations: 
          - Describe
        host: "*"
      - resource:
          type: cluster
        operations: 
          - Describe
          - DescribeConfigs
        host: "*"
