apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: ui
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operation: DescribeConfigs
        host: "*"
      - resource:
          type: group
          name: "*"
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: cluster
          name: "kafka-cluster"
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: cluster
          name: "kafka-cluster"
          patternType: literal
        operation: DescribeConfigs
        host: "*"
