apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: a-quotes
  namespace: kafka-cluster
spec:
  config: {}
  partitions: 1
  replicas: 3
  topicName: a_quotes
