kind: Secret
apiVersion: v1
metadata:
  name: akhq-config
  namespace: idaas
data:
  application.yml: >-
    YWtocToKICBjb25uZWN0aW9uczoKICAgIGRvY2tlci1rYWZrYS1zZXJ2ZXI6CiAgICAgIHByb3BlcnRpZXM6CiAgICAgICAgYm9vdHN0cmFwLnNlcnZlcnM6ICJpZGFhcy1rYWZrYS1ib290c3RyYXA6OTA5MiIK
type: Opaque
