- hosts: localhost
  name: Install AMQ Streams Monitoring Demo
  vars:
    cluster_project: kafka-cluster
    grafana_user: admin
    grafana_password: admin
    insecure_skip_tls_verify: true
    delete_demo: false
  tasks:

    - name: Define domain
      set_fact:
        domain : "{{ server | regex_replace('https://api.') | regex_replace(':6443')   }}"

    - name: Include AMQ Streams role
      include_role:
        name: streams

    - name: Include Monitoring role
      include_role:
        name: monitoring
