- hosts: localhost
  name: Install AMQ Streams Monitoring Demo
  vars:
    cluster_project: kafka-cluster
    grafana_project: '{{ cluster_project  }}'
    console_project: '{{ cluster_project  }}'
    grafana_user: admin
    grafana_password: admin
    insecure_skip_tls_verify: true
    verify_tls: false
    delete_demo: false
  tasks:
    - name: Check Required Parameters
      ansible.builtin.fail:
        msg: "This playbook requires 'server' and 'token' to be defined"
      when:
        - (server is undefined) or (token is undefined) or (server | length == 0) or (token | length == 0)
      ignore_errors: false

    - name: Define domain
      ansible.builtin.set_fact:
        domain: "{{ server | regex_replace('https://api.') | regex_replace(':6443') }}"

    - name: Set Subdomain
      ansible.builtin.set_fact:
        route_subdomain: "apps.{{ domain }}"

    - name: Include AMQ Streams role
      ansible.builtin.include_role:
        name: streams

    - name: Include Grafana role
      ansible.builtin.include_role:
        name: grafana

    - name: Include Console role
      ansible.builtin.include_role:
        name: console

    # - name: Include kafka-ui role
    #   ansible.builtin.include_role:
    #     name: kafka-ui
