- name: Install AMQ Streams Monitoring Demo
  hosts: localhost
  vars:
    cluster_project: streams
    grafana_project: '{{ cluster_project  }}'
    console_project: '{{ cluster_project  }}'
    apicurio_registry_project: '{{ cluster_project }}'
    streams_kafka_cluster_name: my-cluster
    grafana_user: admin
    grafana_password: admin

    streamshub_keycloak_client_id: streamshub
    streamshub_keycloak_client_secret: 9IAuKgbRcEUTU4mjeUUTY25P6IKo0B6L # not a real secret, just for demo purposes
    streamshub_keycloak_realm: streamshub

    keycloak_project: streams-keycloak

    insecure_skip_tls_verify: true
    verify_tls: false
    delete_demo: false
  tasks:
    - name: Check Required Parameters
      ansible.builtin.fail:
        msg: "This playbook requires 'server' and 'token' to be defined"
      when:
        - (server is undefined) or (token is undefined) or (server | length == 0) or (token | length == 0)
      ignore_errors: false
      tags: [kafka, console, registry]

    - name: Define domain
      ansible.builtin.set_fact:
        domain: "{{ server | regex_replace('https://api.') | regex_replace(':6443') }}"
      tags: [kafka, console, registry]

    - name: Set Subdomain
      ansible.builtin.set_fact:
        route_subdomain: "apps.{{ domain }}"
      tags: [kafka, console, registry]

    - name: Include AMQ Streams role
      ansible.builtin.include_role:
        name: kafka
        apply:
          tags: [kafka]
      tags: [kafka]

    - name: Include Grafana role
      ansible.builtin.include_role:
        name: grafana

    - name: Include Console role
      ansible.builtin.include_role:
        name: console
        apply:
          tags: [console]
      tags: [console]

    - name: Include Keycloak role
      ansible.builtin.include_role:
        name: keycloak

    - name: Include Schema Registry
      ansible.builtin.include_role:
        name: registry
        apply:
          tags: [registry]
      tags: [registry]
